### ISSUE TITLE
backblaze b2 file upload failed

### ISSUE THREAD

**Issue by Oliboy50** [Oliboy50/blindtester#34]
```shell
2020-07-06T15:10:14.749760+00:00 app[web.1]: [backblazeb2] retrying post https://pod-000-1125-06.backblaze.com/b2api/v2/b2_upload_file/25f51e6f23d4f96e6b8b0117/c002_v0001125_t0044
2020-07-06T15:10:15.752934+00:00 app[web.1]: [backblazeb2] retrying post https://pod-000-1125-06.backblaze.com/b2api/v2/b2_upload_file/25f51e6f23d4f96e6b8b0117/c002_v0001125_t0044
2020-07-06T15:10:16.756038+00:00 app[web.1]: [backblazeb2] retrying post https://pod-000-1125-06.backblaze.com/b2api/v2/b2_upload_file/25f51e6f23d4f96e6b8b0117/c002_v0001125_t0044
2020-07-06T15:10:17.758812+00:00 app[web.1]: [backblazeb2] retrying post https://pod-000-1125-06.backblaze.com/b2api/v2/b2_upload_file/25f51e6f23d4f96e6b8b0117/c002_v0001125_t0044
2020-07-06T15:10:17.759951+00:00 app[web.1]: [backblazeb2] b2 file upload failed Error: Request body larger than maxBodyLength limit
2020-07-06T15:10:17.759952+00:00 app[web.1]: at RedirectableRequest.write (/home/node/app/node_modules/follow-redirects/index.js:97:24)
2020-07-06T15:10:17.759953+00:00 app[web.1]: at RedirectableRequest.end (/home/node/app/node_modules/follow-redirects/index.js:116:8)
2020-07-06T15:10:17.759953+00:00 app[web.1]: at dispatchHttpRequest (/home/node/app/node_modules/axios/lib/adapters/http.js:276:11)
2020-07-06T15:10:17.759954+00:00 app[web.1]: at new Promise (<anonymous>)
2020-07-06T15:10:17.759954+00:00 app[web.1]: at httpAdapter (/home/node/app/node_modules/axios/lib/adapters/http.js:21:10)
2020-07-06T15:10:17.759954+00:00 app[web.1]: at dispatchRequest (/home/node/app/node_modules/axios/lib/core/dispatchRequest.js:52:10)
2020-07-06T15:10:17.759955+00:00 app[web.1]: at async upload (/home/node/app/src/core/api/backblazeb2.js:84:21)
2020-07-06T15:10:17.759956+00:00 app[web.1]: at async storeNewFileForUrlAndId (/home/node/app/src/core/filesStorage/backblazeb2.js:25:24)
2020-07-06T15:10:17.759956+00:00 app[web.1]: at async getFileDataForUrl (/home/node/app/src/core/fileFinder.js:49:16) {

2020-07-06T15:10:17.760274+00:00 app[web.1]: (node:15) UnhandledPromiseRejectionWarning: Error: [backblazeb2] b2 file upload failed
2020-07-06T15:10:17.760275+00:00 app[web.1]: at upload (/home/node/app/src/core/api/backblazeb2.js:100:13)
2020-07-06T15:10:17.760378+00:00 app[web.1]: (node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20)

```

**Comment by Oliboy50** [comment]
should use the following in axios config object:

```js
maxContentLength: Infinity,
maxBodyLength: Infinity
```
